### ISSUE TITLE
Portal RTX is not working with last NVIDIA drivers

### ISSUE THREAD

**Issue by jgmatu** [ValveSoftware/dxvk#14]
**Describe the bug**

Running portal RTX is not working
Steam release version until 9 Dec 2023.
Nvidia 4070ti RTX
Driver: 546.29.0
Vulkan: 1.3.260
Steam

_Important logs wrapper.cpp_

warn: [06.12.2023 19-28-53][streamline][error]wrapper.cpp:408[vkCreateDevice] vkCreateDevice failed
err: DxvkAdapter: Failed to create device

**Steps to reproduce the behavior**

Go to game on your steam library.
Click on play.
The game will not launch anymore.

**Expected behavior**

The game initialize and I can see the main game menu.
The game worked on January 2023

**Attached files**

Release version config files.

[dxvk.txt](https://github.com/ValveSoftware/dxvk/files/13626147/dxvk.txt)
[hl2_d3d9.log](https://github.com/ValveSoftware/dxvk/files/13626148/hl2_d3d9.log)
[hl2_d3d9.txt](https://github.com/ValveSoftware/dxvk/files/13626149/hl2_d3d9.txt)
[metrics.txt](https://github.com/ValveSoftware/dxvk/files/13626150/metrics.txt)
[rtx.txt](https://github.com/ValveSoftware/dxvk/files/13626151/rtx.txt)
[steam_appid.txt](https://github.com/ValveSoftware/dxvk/files/13626152/steam_appid.txt)
[thirdpartylegalnotices.txt](https://github.com/ValveSoftware/dxvk/files/13626153/thirdpartylegalnotices.txt)

**Comment by kisak-valve** [comment]
Hello @jgmatu, you've come across a downstream fork of DXVK which is exclusively used for integration of the project into Proton.

Please report this issue on the compatibility report for the game (https://github.com/ValveSoftware/Proton/issues/6367) or to the upstream issue tracker (https://github.com/doitsujin/dxvk).
