### ISSUE TITLE
no tags past v0.71

### ISSUE THREAD

**Issue by aviau** [ValveSoftware/dxvk#7]
Hello!

I have noticed that there are no tags past v0.71, is there a reason for this?

I am in the process of packaging dxvk for Debian and we would find tags useful as we usually use them in scripts to download the latest tarballs and to monitor the repository for new versions.

Cheers,

**Comment by tycho** [comment]
I pushed tags out.

**Comment by tingvarsson** [comment]
Shouldnt you use upstream dxvk as base instead? This is the version used in proton.

**Comment by tycho** [comment]
Indeed. Although there usually aren't any differences between the ValveSoftware/dxvk repository and upstream dxvk (aside from being behind).

@aviau I'd recommend building from here instead https://github.com/doitsujin/dxvk

**Comment by aviau** [comment]
Yes I should! Thank you for pointing that out, oops!

**Comment by loathingKernel** [comment]
Would it be possible to push the latest git tags again?
Would it be nice to have it display a proper version number
instead of v0.90-[huge number of commits] for local proton builds.

**Comment by tycho** [comment]
@loathingKernel Done!
